name: twitter
author: sh4869 <nobuk4869@gmail.com> # name <email>
homepage: https://github.com/sh4869/twitter.dart # https://github.com/user/repo
version: 0.5.1
environment:
  sdk: ">=2.1.0 <3.0.0"
description: Twitter API Library
dependencies:
  oauth:
    git:
      url: git://github.com/sh4869/oauth.dart.git
      ref: develop
  http: '>=0.11.2 <0.12.0'
dev_dependencies:
  test: '^1.5.1'
